"""edit User model add userMixin class for authentication

Revision ID: 424dd9c989ed
Revises: 73bd6f928eaa
Create Date: 2021-04-25 20:13:41.670359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424dd9c989ed'
down_revision = '73bd6f928eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
