"""Initial Migration

Revision ID: 4b26166a492a
Revises: f453b8244bd2
Create Date: 2021-11-13 11:01:43.006644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b26166a492a'
down_revision = 'f453b8244bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'upvotes', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='unique')
    # ### end Alembic commands ###
