"""Add Downvote table and set up relationships with pitch and user table

Revision ID: 607e5eb79b5e
Revises: 8c38f6520afb
Create Date: 2021-04-26 20:50:39.670890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607e5eb79b5e'
down_revision = '8c38f6520afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downvote_count', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downvotes')
    # ### end Alembic commands ###
