"""empty message

Revision ID: 62d92f16ee22
Revises: 
Create Date: 2021-11-09 23:01:23.880333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d92f16ee22'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('upvote_count', sa.Integer(), nullable=True))
    op.drop_column('upvotes', 'pitch_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('pitch_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('upvotes', 'upvote_count')
    # ### end Alembic commands ###
