"""edit upvote table update pitch_count to upvote_count

Revision ID: 8c38f6520afb
Revises: a2c948540111
Create Date: 2021-04-26 07:24:38.670009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c38f6520afb'
down_revision = 'a2c948540111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('upvote_count', sa.Integer(), nullable=True))
    op.drop_column('upvotes', 'pitch_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('pitch_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('upvotes', 'upvote_count')
    # ### end Alembic commands ###
