"""update user model add profile_picture column

Revision ID: 928a5f141528
Revises: ef9a790947d5
Create Date: 2021-04-26 03:15:56.915044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928a5f141528'
down_revision = 'ef9a790947d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
