"""edit comment to have unique comments

Revision ID: c1b518417526
Revises: 928a5f141528
Create Date: 2021-04-26 06:10:37.303851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b518417526'
down_revision = '928a5f141528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comments', ['comment'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='unique')
    # ### end Alembic commands ###
