"""empty message

Revision ID: f453b8244bd2
Revises: 4e3bc3cbed0f
Create Date: 2021-11-13 10:38:05.695088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f453b8244bd2'
down_revision = '4e3bc3cbed0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'upvotes', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='unique')
    # ### end Alembic commands ###
